"""VAE models and components."""

from src.models.base import (
    BaseDecoder,
    BaseEncoder,
    BaseLikelihood,
    BaseLoss,
    BasePosterior,
    BasePosteriorDistribution,
    BasePrior,
    BasePriorDistribution,
)
from src.models.registry import (
    DECODER_REGISTRY,
    ENCODER_REGISTRY,
    LIKELIHOOD_REGISTRY,
    LOSS_REGISTRY,
    POSTERIOR_REGISTRY,
    PRIOR_REGISTRY,
    build_vae_from_config,
    get_decoder,
    get_encoder,
    get_likelihood,
    get_loss,
    get_posterior,
    get_prior,
    register_decoder,
    register_encoder,
    register_likelihood,
    register_loss,
    register_posterior,
    register_prior,
)
from src.models.types import LossOutput, VAEOutput
from src.models.vae import VAE

__all__ = [
    "VAE",
    "VAEOutput",
    "LossOutput",
    "BaseEncoder",
    "BaseDecoder",
    "BasePosterior",
    "BasePrior",
    "BaseLikelihood",
    "BaseLoss",
    "BasePosteriorDistribution",
    "BasePriorDistribution",
    "ENCODER_REGISTRY",
    "DECODER_REGISTRY",
    "POSTERIOR_REGISTRY",
    "PRIOR_REGISTRY",
    "LIKELIHOOD_REGISTRY",
    "LOSS_REGISTRY",
    "register_encoder",
    "register_decoder",
    "register_posterior",
    "register_prior",
    "register_likelihood",
    "register_loss",
    "get_encoder",
    "get_decoder",
    "get_posterior",
    "get_prior",
    "get_likelihood",
    "get_loss",
    "build_vae_from_config",
]

